### ISSUE TITLE
binary download with stream output

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#124]
As far as I can see, the binary download reads the complete file into memory, then writes this buffer to a file. There are natural limits for this, e.g., for large files, so probably the whole contents should not be read into memory.
Also, for my use case, I would be happy to have an interface in the client code that allows writing to a stream instead of the file system, just as with `ClientHelper.getWholeFile()`, would that be possible?

**Comment by kuenishi** [comment]
There's an implicit assumption that the size of a file to be downloaded fits well in memory, like <10MB at largest. This is why the client API does not have API for OutputStream, to force applications to download only small files.

This is also because [Mesos HTTP endpoint API](http://mesos.apache.org/documentation/latest/endpoints/files/download/) does not expose good API for streaming download (e.g. `Range` header).  As downloading large files like more than that size requires smarter retry logic, I don't think just connecting InputStream from Mesos HTTP endpoint to OutputStream to clients at Retz server doesn't work well.

Note that Retz has [foolproof safe guard on file size](https://github.com/retz/retz/blob/master/retz-common/src/main/java/io/github/retz/protocol/DownloadFileRequest.java#L29), limiting max size to 64MB to save the server from single large file download crashing the process.

**Comment by tgpfeiffer** [comment]
OK, so I guess there are a couple of issues here. First, let me state that in our case I will very soon work with output files larger than 64MB so this issue is quite important for me. As per your comment on https://github.com/retz/retz/blob/master/retz-server/src/main/java/io/github/retz/web/JobRequestHandler.java#L169 it seems you see this the same ;-)
Once the server supports piping the data through to the client, the client should expose a similar "InputStream to OutputStream" function without reading all the data into memory. I don't think there is a need for a particularly smart retry logic here. As you said, we are limited by the Mesos API, and if that does not support retry, then so be it.

**Comment by kuenishi** [comment]
OK, I understand your need and thank you for contribution (I've just merged #125).

**Comment by kuenishi** [comment]
https://github.com/retz/retz/commit/ad653e07258831b188cb4fcd7ab9722c183cb9a0 is a client-side optimization included in 0.2.3. Server side optimization may happen around [here](https://github.com/retz/retz/blob/0.2.3/retz-server/src/main/java/io/github/retz/web/JobRequestHandler.java#L177-L187).

**Comment by kuenishi** [comment]
Thanks to @dtaniwaki it's done!
