### ISSUE TITLE
Complex rules for resource offer selection

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#129]
Mesos hands out resource offers to frameworks and those frameworks can decide which of the available offers they want to use, or if they want to decline all of them and wait for a better offer, or if they want to give up after some time.

Retz reverses this and asks the users to specify what resources they need and then matches those requirements to the offers received by Mesos.

I think the Retz way is simple and good (as the user does not have to write logic to accept or deline offers), but I have a couple of use cases now where I wish I could submit some logic to either select an "appropriate" offer from the ones that are available or modify my resource request to match what is available.

Some examples:
- I have GPU nodes and non-GPU nodes. The jobs that do not require a GPU shall be executed on a non-GPU node if one is available. If none is available, then fall back to a GPU node.
- I want to launch a job that uses "all available GPUs" on a node.
- As an extension of the point above, say I want to launch multiple jobs, but all of them together should use 8 GPUs and 1 GB of RAM for each GPU". So maybe *(4 GPUs, 4 GB RAM)* on host A, *(3 GPUs, 3 GB RAM)* on host B, *(1 GPU, 1 GB RAM)* on host C, but a different distribution would also be fine.

Probably this is not an everyday use case, but I was wondering if you have any ideas on how such a thing *could* be implemented in the context of a task queue. I was thinking that this reduces to the question: "How can the user specify their own function _pickOffer: List&lt;Offer&gt; → Option&lt;Offer&gt;_ (or so) with a task, instead of a fixed resource requirement?"

Here are two fancy ideas that I had:
1. Send a string that describes a function in an easily embeddable, safe scripting language (Lua?) to the server when submitting a task.
2. Serialize the logic to pick an offer in something like [JsonLogic](http://jsonlogic.com/).

I guess nobody would ever use this from the command line, only from the Retz client API. In that case, instead of writing

```java
new Job(appName, command, new Properties(),
        2, 1024, 1, 0)
```

you could write

```java
new Job(appName, command, new Properties(),
        "(serialized function to pick an offer that provides what you want)")
```

This is just one idea that I had, but mainly I wanted to ask for your opinion about the whole issue of selecting offers based on availability instead of specifying fixed requirements.

**Comment by kuenishi** [comment]
That ideas are very interesting! I'd love that making offer accepting logic programmable. My plan have been making planners pluggable via dependency injection ( but it's still just a plan, starting [here](https://github.com/retz/retz/blob/master/retz-server/src/main/java/io/github/retz/scheduler/PlannerFactory.java) and inputs to custom planners should be also sendable through client library). I have [a plan to add another planner](https://github.com/retz/retz/issues/121) that exposes fairness among users. A programmable planner will also be able to be put there. 

On each example,

> I have GPU nodes and non-GPU nodes. The jobs that do not require a GPU shall be executed on a non-GPU node if one is available. If none is available, then fall back to a GPU node.

I think this use case is general enough that we can put this logic into the default NaivePlanner. Its code is not just clean enough ..

> I want to launch a job that uses "all available GPUs" on a node.
> As an extension of the point above, say I want to launch multiple jobs, but all of them together should use 8 GPUs and 1 GB of RAM for each GPU". So maybe (4 GPUs, 4 GB RAM) on host A, (3 GPUs, 3 GB RAM) on host B, (1 GPU, 1 GB RAM) on host C, but a different distribution would also be fine.

This would also be fair enough, and would be also possible with custom planner, but combination of all features one want may explode when we develop each planner for each use case.

The variety of scheduling policy would infinite and may explode. At this point we have make decision on tradeoff, between variety of planners, flexibility of programmable planner, and safety (a guarantee that all jobs are reasonably scheduled, otherwise skipped or killed). Safety would be guaranteed under strictness that conflicts with flexibility.  Variety of scheduling policy and planners would make it hard to design clean planner interface.

**Comment by tgpfeiffer** [comment]
If I could implement a custom planner that allows to realize a custom offer accepting logic, that would be amazing!

**Comment by kuenishi** [comment]
Although the custom planner is still experimental I'm going to close this. Feel free to reopen for more discussion.
