### ISSUE TITLE
Retz claims all the offers in the cluster

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#63]
At the moment it seems that Retz is caching all the offers that were offered by the server and never releases them until a job is submitted. In particular that means that other frameworks cannot launch their jobs because they get no offers.

**Comment by kuenishi** [comment]
There's [a configurable limit of the number of offers](https://github.com/retz/retz/blob/f172d61b1cf7001383f107ee7961d4888ae54851/retz-common/src/main/java/io/github/retz/cli/FileConfiguration.java#L59-L60), so that Retz won't take all offers of the cluster. Maybe default value of 16 could be too big for a small cluster?

**Comment by tgpfeiffer** [comment]
OK, thank you. I didn't see that option, but it seems to work as intended.
